name: Main action
on:
  push:
    branches:
      - master

env:
  NODE_ENV: production
  
jobs:
  main:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
      
    - name: Cache dependencies
      uses: actions/cache@v1
      with:
        path: node_modules
        key: ${{ runner.OS }}-npm-cache-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.OS }}-npm-cache-

    - name: Install
      run: npm install & touch 'test'
    
    - name: Lint
      run: npm run lint && ls

    - name: Test
      run: npm run test && ls
    
    - name: Build
      run: npm run build && ls

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.DEPLOY_ACCESS_TOKEN }}
        BRANCH: gh-pages
        FOLDER: dist
