name: Main action
on:
  push:
    branches:
      - 'master'
env:
  NODE_ENV: production
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          
      - name: Lint
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - uses: bahmutov/npm-install@v1
        run: npm run lint

      - name: Build
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - uses: bahmutov/npm-install@v1
        run: npm run build

      - name: Test
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - uses: bahmutov/npm-install@v1
        run: npm run test
        
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.DEPLOY_ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist
