name: Main action
on:
  push:
    branches:
      - master

env:
  NODE_ENV: production
  
jobs:
  main:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    
    - name: Cache dependencies
      id: cache
      uses: actions/cache@v1
      run: echo "::set-output name=dir::$(npm config get cache)"
      with:
        path: ${{ steps.npm-cache.outputs.dir }}
        key: ${{ runner.OS }}-npm-cache-${{ hashFiles('**/package-lock.json') }}
        restore-keys: ${{ runner.OS }}-npm-cache-

    - name: Install
      if: steps.cache.outputs.cache-hit != 'true'
      uses: jaid/action-npm-install@v1.2.1
    
    - name: Lint
      run: npm run lint
      
    - name: Test
      run: npm run test
    
    - name: Build
      run: npm run build

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.DEPLOY_ACCESS_TOKEN }}
        BRANCH: gh-pages
        FOLDER: dist
