name: Main action
on:
  push:
    branches:
      - master

env:
  NODE_ENV: production
  
jobs:
  main:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1

    - name: Install
      uses: jaid/action-npm-install@v1.2.1
    
    - name: Lint
      run: npm run lint && touch 'test' && ls

    - name: Test
      run: npm run test && ls
    
    - name: Build
      run: npm run build && ls

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.DEPLOY_ACCESS_TOKEN }}
        BRANCH: gh-pages
        FOLDER: dist
