name: Main action
on:
  push:
    branches:
      - master

jobs:
  main:
    container:
      image: gerardojunior/nodejs:stable
      env:
        NODE_ENV: production

    steps:
    - uses: actions/checkout@v1

    - name: Install
    - run: npm install
    
    - name: Lint
    - run: npm run lint

    - name: Test
    - run: npm run test
    
    - name: Build
    - run: npm run build

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.DEPLOY_ACCESS_TOKEN }}
        BRANCH: gh-pages
        FOLDER: dist