name: Build and Deploy
on:
  push:
    branches:
      - 'master'
env:
  NODE_ENV: production
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Install
        run: npm install
      
      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build
      
      - name: Test
        run: npm run test
        
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.DEPLOY_ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build
